site_name: V1CeVersa's Notebook
site_url: https://note.v1ceversaa.cc
repo_name: V1CeVersaa/notebook
repo_url: https://github.com/V1CeVersaa/V1CeVersaa.github.io
copyright: Copyright &copy; 2024 V1CeVersa

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/V1CeVersaa
    analytics:
        provider: vercel

theme:
    name: material
    custom_dir: overrides
    language: 'zh'
    icon:
        logo: material/notebook-outline
    features:
        - content.code.annotate
        - content.action.edit
        - toc.follow
        - navigation.tracking
        - navigation.tabs
        - navigation.prune
        - navigation.indexes
        - navigation.top
        - search.share
        - search.highlight
        - search.suggest
    font: false
    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: brown
          accent: brown
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          toggle:
              icon: material/weather-night #图标，月亮
              name: Switch to light mode

plugins:
    - search
    - statistics

nav:
    - Home: index.md
    - Computer Science:
          - Computer Science/index.md
          - Programing Utils:
                - Computer Science/Programming Utils/index.md
                - Shell: Computer Science/Programming Utils/Shell.md
                - Git: Computer Science/Programming Utils/Git.md
                - Linux: Computer Science/Programming Utils/Linux.md
                - Docker: Computer Science/Programming Utils/Docker.md
                - GNU Make & CMake: Computer Science/Programming Utils/GNU Make.md
                - Regular Expression: Computer Science/Programming Utils/Regular Expression.md
                - Tmux Cheatsheet: Computer Science/Programming Utils/tmux.md
          - Programing Language:
                - Computer Science/Programming Language/index.md
                - C:
                      - Computer Science/Programming Language/C/index.md
                      - Basic Syntax: Computer Science/Programming Language/C/topic1.md
                      - Array, Pointer and String: Computer Science/Programming Language/C/topic2.md
                      - Memory Management: Computer Science/Programming Language/C/topic3.md
                      - Standard Library: Computer Science/Programming Language/C/topic4.md
                - C++:
                      - Computer Science/Programming Language/C++/index.md
                      - Basic Syntax: Computer Science/Programming Language/C++/Basic Syntax.md
                      - Object Oriented Programming: Computer Science/Programming Language/C++/Object Oriented Programming.md
                      - Standard Library: Computer Science/Programming Language/C++/Standard Library.md
                      - CS106L 笔记: Computer Science/Programming Language/C++/CS106L.md
                - Python:
                      - Computer Science/Programming Language/Python/index.md
                      - Variable and Types: Computer Science/Programming Language/Python/VAT.md
                      - Input and Output: Computer Science/Programming Language/Python/IO.md
                      - Object Oriented Programming: Computer Science/Programming Language/Python/OOP.md
                      - Standard Library: Computer Science/Programming Language/Python/Lib-std.md
                    #   - Pwntools: Computer Science/Programming Language/Python/Lib-Pwntools.md
                      - Numpy: Computer Science/Programming Language/Python/Lib-Numpy.md
                    #   - Pandas: Computer Science/Programming Language/Python/Lib-Pandas.md
                - Rust:
                      - Computer Science/Programming Language/Rust/index.md
                      - Basic Syntax: Computer Science/Programming Language/Rust/Basic Syntax.md
                - Go:
                      - Computer Science/Programming Language/Go/index.md
                      - Basic Syntax: Computer Science/Programming Language/Go/Basic Syntax.md
                - OCaml:
                      - Computer Science/Programming Language/OCaml/index.md
          - Algorithms & DS:
                - Computer Science/Algorithm/index.md
                - FDS Collection I: Computer Science/Algorithm/FDS I.md
                - FDS Collection II: Computer Science/Algorithm/FDS II.md
                - Advanced Trees: Computer Science/Algorithm/Lec 1.md
                - Advanced Heaps: Computer Science/Algorithm/Lec 2.md
                - Algorithms I: Computer Science/Algorithm/Lec 3.md
                - Algorithms II: Computer Science/Algorithm/Lec 4.md
                - Algorithms III: Computer Science/Algorithm/Lec 5.md
          - Principles of Compilers:
                - Computer Science/Compilers/index.md
                - Topic 1：词法分析: Computer Science/Compilers/1 lex.md
                - Topic 2：语法分析: Computer Science/Compilers/2 parse.md
                - Topic 3：抽象语法: Computer Science/Compilers/3 ast.md
                - Topic 4：语义分析: Computer Science/Compilers/4 semantic.md
                - Topic 5：激活记录: Computer Science/Compilers/5 activation.md
          - Quantum Computing:
                - Computer Science/Quantum Computing/index.md
                - Quantum Basis: Computer Science/Quantum Computing/basis.md
                - Quantum Machine Learning: Computer Science/Quantum Computing/QML.md
          - Blockchain:
                - Blockchain Basis: Computer Science/Blockchain/Blockchain.md
                - Ethereum:
                      - Computer Science/Blockchain/Ethereum/index.md
                      - Solidity: Computer Science/Blockchain/Ethereum/Solidity.md
                      - ERC Standard: Computer Science/Blockchain/Ethereum/ERC.md
          - Web:
                - Computer Science/Web/index.md
                - CSS: Computer Science/Web/CSS.md
                - HTML: Computer Science/Web/HTML.md
                - JavaScript:
                      - Javascript: Computer Science/Web/Javascript/Javascript.md
                      - Vue: Computer Science/Web/Javascript/Vue.md
                - YAML: Computer Science/Web/YAML.md
          - CTF:
                - DNS Protocol: Computer Science/CTF/DNS.md
                - Cryptography:
                      - Computer Science/CTF/Crypto/index.md
                      - ECC: Computer Science/CTF/Crypto/ECC.md
    - System:
          - System/index.md
          - General Introduction:
                - CSAPP-A Tour of Computer Systems: System/CSAPP/Chapter1.md
                - The Datacenter as a Computer: System/TDAAC/TDAAC.md
          - Digital Logic:
                - CSAPP-Supplement: System/CSAPP/Supplement.md
          - Presenting and Manipulating Information:
                - CSAPP-Presenting and Manipulating Information: System/CSAPP/Chapter2.md
          - Machine-Level Representation of Programs:
                - CSAPP-Machine-Level Representation of Programs: System/CSAPP/Chapter3.md
                - CSAPP-Optimizing Program Performance: System/CSAPP/Chapter5.md
                - RISC-V Assembly:
                      - System/RISC-V/RISC-V.md
                      - Unprivileged ISA: System/RISC-V/RISC-V-upr.md
                      - Privileged ISA: System/RISC-V/RISC-V-pr.md
                - x86 Assembly:
                      - System/x86 Assembly/x86.md
          - Processor Architecture:
                - ZJU SYS II-Processor: System/ZJU SYS/SysII-Processor.md
                - CSAPP-Processor Architecture: System/CSAPP/Chapter4.md
                - ZJU SYS III-Quantitative Analysis: System/ZJU SYS/SysIII-Quantitative.md
                - ZJU SYS III-Instruction Level Parallelism: System/ZJU SYS/SysIII-ILP.md
          - Memory Hierarchy:
                - CSAPP-The Memory Hierarchy: System/CSAPP/Chapter6.md
                - ZJU SYS III-Memory Hierarchy: System/ZJU SYS/SysIII-Memory.md
                - OSC-Main Memory: System/OSC/topic5.md
                - OSC-Virtual Memory: System/OSC/topic6.md
                - OSC-Mass-Storage Structure: System/OSC/topic7.md
                - OSC-I/O Systems: System/OSC/topic8.md
                - OSC-File System: System/OSC/topic9.md
                - OSTEP-Memory Virtualization: System/OSTEP/topic2.md
          - Running Programs on a System:
                - OSC-OS Structure: System/OSC/topic0.md
                - CSAPP-Linking: System/CSAPP/Chapter7.md
                - CSAPP-Exceptional Control Flow: System/CSAPP/Chapter8.md
                - CSAPP-Virtual Memory: System/CSAPP/Chapter9.md
          - Process Management & Synchronization:
                - OSC-Process & Thread: System/OSC/topic1.md
                - OSC-Scheduling: System/OSC/topic2.md
                - OSTEP-CPU Virtualization: System/OSTEP/topic1.md
                - OSC-Synchronization: System/OSC/topic3.md
                - OSC-Deadlock: System/OSC/topic4.md
                - OSTEP-Concurrency: System/OSTEP/topic3.md
          - Interacting and Communicating with a System:
                - CSAPP-System-Level IO: System/CSAPP/Chapter10.md
                - CSAPP-Network Programming: System/CSAPP/Chapter11.md
                - CSAPP-Concurrent Programming: System/CSAPP/Chapter12.md
          - Digital Design & Computer Architecture:
                - DDCA-Combinational Logic: System/DDCA/Chapter2.md
                - DDCA-Sequential Logic: System/DDCA/Chapter3.md
                - DDCA-Hardware Description Language: System/DDCA/Chapter4.md
                - DDCA-Digital Building Blocks: System/DDCA/Chapter5.md
                - DDCA-Architecture: System/DDCA/Chapter6.md
                - DDCA-Microarchitecture: System/DDCA/Chapter7.md
                - DDCA-Memory Systems: System/DDCA/Chapter8.md
          - Computer Organization & Design:
                - COAD-Computer Abstractions and Technology: System/COAD/Chapter1.md
                - COAD-Arithmetic for Computers: System/COAD/Chapter2.md
                - COAD-Instructions Language of the Computer: System/COAD/Chapter3.md
                - COAD-The Processor: System/COAD/Chapter4.md
                - COAD-Large and Fast Exploiting Memory Hierarchy: System/COAD/Chapter5.md
          - Hardware Description Language:
                - Verilog: System/HDL/Verilog.md
                - Chisel: System/HDL/Chisel.md
          - Booklist:
                - CSAPP: System/CSAPP/CSAPP.md
                - COAD: System/COAD/COAD.md
                - DDCA: System/DDCA/DDCA.md
                - OSC: System/OSC/OSC.md
                - OSTEP: System/OSTEP/OSTEP.md
    - AI:
          - AI/index.md
          - 人工智能逻辑:
                - AI/AIL/index.md
                - 第1节：绪论: AI/AIL/1 Introduction.md
                - 第2节：命题逻辑: AI/AIL/2 Proposition.md
                - 第3节：一阶逻辑: AI/AIL/3 One Order.md
                - 第4节：描述逻辑: AI/AIL/4 Description.md
                - 第5节：缺省逻辑: AI/AIL/5 Default.md
                - 第6节：回答集编程: AI/AIL/6 Answer Set.md
                - 第7节：经典抽象论辩理论: AI/AIL/7 Classical Debate.md
                - 第8节：结构化论辩理论: AI/AIL/8 Structured Debate.md
                - 第9节：概率理论与贝叶斯网络: AI/AIL/9 Bayesian.md
                - 第10节：归纳推理与归纳逻辑编程: AI/AIL/10 Inductive.md
                - 第11节：概率论辩: AI/AIL/11 Probabilistic Debate.md
          - 机器学习基本知识:
                - AI/ML Basis/index.md
                - 第1章：绪论: AI/ML Basis/1 Intro.md
                - 第2章：模型评估: AI/ML Basis/2 Evaluation.md
                - 第3章：线性模型: AI/ML Basis/3 Linear.md
                - 第4章：决策树: AI/ML Basis/4 Decision.md
                - 第5章：神经网络: AI/ML Basis/5 Neural.md
                - 第6章：支持向量机: AI/ML Basis/6 SVM.md
                - 第7章：贝叶斯分类器: AI/ML Basis/7 Bayes.md
                - 第8章：集成学习: AI/ML Basis/8 Ensemble.md
                - 第9章：聚类: AI/ML Basis/9 Clustering.md
                - 第10章：降维与度量学习: AI/ML Basis/10 Dimensionality.md
                - 第11章：特征选择与稀疏学习: AI/ML Basis/11 Feature.md
                - 第12章：计算学习理论: AI/ML Basis/12 Computational.md
                - 第13章：半监督学习: AI/ML Basis/13 Semi-Supervised.md
                - 第14章：概率图模型: AI/ML Basis/14 Graphical.md
                - 第15章：规则学习: AI/ML Basis/15 Rule.md
                - 第16章：强化学习: AI/ML Basis/16 Reinforcement.md
          - 机器学习理论导引:
                - AI/ML Theory/index.md
                - 第1章：预备知识: AI/ML Theory/1 Preliminaries.md
                - 第2章：可学性: AI/ML Theory/2 Learnability.md
                - 第3章：复杂度: AI/ML Theory/3 Complexity.md
                - 第4章：泛化界: AI/ML Theory/4 Generalization.md
                - 第5章：稳定性: AI/ML Theory/5 Stability.md
                - 第6章：一致性: AI/ML Theory/6 Consistency.md
                - 第7章：收敛率: AI/ML Theory/7 Convergence.md
                - 第8章：遗憾界: AI/ML Theory/8 Regret.md
          - Foundations of Machine Learning:
                - AI/ML Foundations/index.md
          - Intro to Online Learning: 
                - AI/Online Learning/index.md
                - "Topic 1: Online Learning and OCO": AI/Online Learning/Lecture 1.md
                - "Topic 2: Multi-Armed Bandits": AI/Online Learning/Lecture 2.md
          - Mathematical Analysis of Machine Learning Algorithms:
                - AI/Math Analysis/index.md
                - 1 Introduction: AI/Math Analysis/1 Intro.md
                - 2 Probability Inequalities: AI/Math Analysis/2 Probability.md
                - 3 Uniform Convergence: AI/Math Analysis/3 Convergence.md
                - 4 Empirical Covering Number Analysis: AI/Math Analysis/4 Covering.md
                - 5 Covering Number Estimates: AI/Math Analysis/5 Estimates.md
          - Foundations of Reinforcement Learning:
                - AI/RL Theory/index.md
          - Introduction to Casual Inference:
                - AI/Causal Inference/index.md
          - 机器学习框架:
                - AI/ML Framework/index.md
          - Deep Learning for NLP:
                - AI/CS224N/index.md
          - Deep Learning for CV:
                - AI/Computer Vision/index.md
                - Part 1：线性分类器与简单神经网络: AI/Computer Vision/part 1.md
                - Part 2：卷积神经网络: AI/Computer Vision/part 2.md
                - Part 3：深度学习 I: AI/Computer Vision/part 3.md
                - Part 4：深度学习 II: AI/Computer Vision/part 4.md
    - Math:
          - Basic Courses: Math/index.md
          - Abstract Algebra:
                - Math/Abstract Algebra/index.md
          - Topics on Analysis:
                - Math/Real Analysis/index.md
                - Mathematical Analysis: Math/Real Analysis/Mathematical Analysis.md
                - Measure: Math/Real Analysis/Measure.md
                - Integration: Math/Real Analysis/Integration.md
          - Optimization:
                - Math/Optimization/index.md
                - Course Introduction: Math/Optimization/1 Introduction.md
                - Basis for Optimizaion: Math/Optimization/2 Smooth.md
                - Descent Method: Math/Optimization/3 Descent.md
                - Acceleration Method: Math/Optimization/4 Acceleration.md
                - Convex Method: Math/Optimization/5 Convex.md
                - Constraint Set: Math/Optimization/6 Constrained.md
                - Structure Optimization: Math/Optimization/7 Structure.md
                - Stochastic Optimization: Math/Optimization/8 Stochastic.md
          - Basic Probability:
                - Math/Probability Basis/index.md
                - Chapter 1-2: Math/Probability Basis/Chapter 1-2.md
                - Chapter 3: Math/Probability Basis/Chapter 3.md
                - Chapter 4: Math/Probability Basis/Chapter 4.md
                - Chapter 5: Math/Probability Basis/Chapter 5.md
          - Advanced Probability:
                - Math/Probability/index.md
                - Laws of Large Numbers: Math/Probability/Chapter 1.md
          - Discrete Mathematics:
                - Math/Discrete Mathematics/Discrete Mathematics.md
                - Propositional Logic: Math/Discrete Mathematics/01 Propositional Logic.md
                - Basic Structures: Math/Discrete Mathematics/02 Basic Structures.md
                - Algorithms: Math/Discrete Mathematics/03 Algorithms.md
                - Number Theory: Math/Discrete Mathematics/04 Number Theory.md
                - Induction and Recursion: Math/Discrete Mathematics/05 Induction and Recursion.md
                - Counting: Math/Discrete Mathematics/06 Counting.md
                - Advanced Counting Techniques: Math/Discrete Mathematics/08 Advanced Counting Techniques.md
                - Relations: Math/Discrete Mathematics/09 Relations.md
                - Graph Theory: Math/Discrete Mathematics/10 Graph Theory.md
                - Trees: Math/Discrete Mathematics/11 Trees.md
    - Research:
          - Research/index.md
          - 1 Dueling Bandits Near Optimal: Research/1 Dueling Bandits Near Optimal.md
          - 2 Action Elimination for RL: Research/2 Action Elimination for RL.md
          - 3 Dueling Bandits with Weak Regret: Research/3 Dueling Bandits with Weak Regret.md
          - 4 Beat the Mean Bandit: Research/4 Beat the Mean Bandit.md
          - 5 Maximum Selection and Ranking: Research/5 Maximum Selection and Ranking under Noisy Comparisons.md
    - Varia:
          - Learning Plan: Varia/Learning Plan.md
          - Typst Learning Report: Varia/Typst.md
          - Environment & Tools: Varia/Envs.md

markdown_extensions:
    - toc:
          permalink: true
          toc_depth: 4
    - meta
    - def_list
    - attr_list
    - md_in_html
    - sane_lists
    - admonition
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.magiclink
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.smartsymbols
    - neoteroi.spantable
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.highlight:
          anchor_linenums: true
          linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.arithmatex:
          generic: true

extra_css:
    - https://gcore.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
    - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
    - css/custom.css
    - css/card.css
    - css/tasklist.css
    - css/flink.css
    - css/more_changelog.css
    - css/neoteroi-mkdocs.css
    - css/fold_toc.css

extra_javascript:
    - css/Javascripts/toc.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    # - Javascripts/mathjax.js
    # - Javascripts/katex.js
    # - Javascripts/tablesort.js
