site_name: V1CeVersa's Notebook
theme: 
  name: material
  language: 'zh'
  icon:
    logo: material/notebook-outline
  # favicon: material/notebook-outline
  # custom_dir: overrides
  features:
    # - header.autohide
    - content.code.annotate
    - content.action.edit
    - toc.follow
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    # - navigation.tabs.sticky
    - search.share
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
  font:
    text: LXGW WenKai Screen
    code: [JetBrains Mono, LXGW WenKai Screen]
  palette:
    # - scheme: default 
    - media: "(prefers-color-scheme: light)" 
      scheme: default  
      primary: brown  
      accent: brown  
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true


extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/custom.css
  - css/card.css
  - css/tasklist.css
  - css/flink.css
  - css/more_changelog.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - Javascripts/mathjax.js
  - Javascripts/katex.js
  # Table Sort
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - Javascripts/tablesort.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/V1CeVersaa

plugins:
  - search

  # - changelog
  # - search
  # - git-revision-date-localized:
  #     type: datetime
  #     timezone: Asia/Shanghai
  #     locale: zh
  #     enable_creation_date: true

nav:
  - Home: index.md
  - Computer Science: 
    - Computer Science/index.md
    - Programing Basis: 
      - Computer Science/Programming Basis/index.md
      - Shell: Computer Science/Programming Basis/Shell.md
      - Linux: Computer Science/Programming Basis/Linux.md
      - Assembly: Computer Science/Programming Basis/Assembly.md
      - MIT Missing Semester: Computer Science/Programming Basis/MIT Missing Semester.md
    - Programing language:
      - Computer Science/Programming Language/index.md
      - C: Computer Science/Programming Language/EVERYTHING begins with C.md
      - C++: Computer Science/Programming Language/C++.md
      - Python: Computer Science/Programming Language/Python saves the world.md
      - Java: Computer Science/Programming Language/Java.md
    - Algorithm: 
      - Computer Science/Algorithm/index.md
      - Discrete Mathematics: Computer Science/Algorithm/Discrete Mathematics.md
      - Fundamental Data Structure: Computer Science/Algorithm/Foundamental Data Structure.md
      - Advanced Data Structure and Alogrithm Analysis: Computer Science/Algorithm/ads.md
      - Algorithms: Computer Science/Algorithm/Algorithms.md
    - System:
      - Computer Science/System/index.md
      - Verilog: Computer Science/System/Verilog.md
      - CSAPP: Computer Science/System/CSAPP.md
      - 计算机系统 I: Computer Science/System/System1.md
    - Web:
      - Computer Science/Web/index.md
      - CSS: Computer Science/Web/CSS.md
      - HTML: Computer Science/Web/HTML.md
      - JavaScript: Computer Science/Web/JavaScript.md
      - YAML: Computer Science/Web/YAML.md
  - Math:
    - Math/index.md
    # - Algebra: Math/Algebra.md
    # - Analysis: Math/Analysis.md
    # - Topology: Math/General Topology.md
  - Reading: 
    - Reading/index.md
    - History: 
      - Reading/The Western Heritage.md
    - Taking Sides:
      - Reading/Taking Sides/index.md
      - Sustainability: Reading/Taking Sides/Sustainability.md
  - Varia: 
    - Learning Plan: Varia/Learning Plan.md
    - Booklist: Varia/Booklist.md