site_name: V1CeVersa's Notebook
copyright: Copyright &copy; 2024 V1CeVersa

theme: 
  name: material
  language: 'zh'
  icon:
    logo: material/notebook-outline
  # favicon: material/notebook-outline
  # custom_dir: overrides
  features:
    # - header.autohide
    - content.code.annotate
    - content.action.edit
    - toc.follow
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    # - navigation.tabs.sticky
    - search.share
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
  font:
    text: LXGW WenKai Screen
    code: [Monaspace Argon Light, JetBrains Mono, LXGW WenKai Screen]
  palette:
    # - scheme: default 
    - media: "(prefers-color-scheme: light)" 
      scheme: default  
      primary: brown  
      accent: brown  
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true


extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - css/custom.css
  - css/card.css
  - css/tasklist.css
  - css/flink.css
  - css/more_changelog.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - Javascripts/mathjax.js
  - Javascripts/katex.js
  # Table Sort
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - Javascripts/tablesort.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/V1CeVersaa

plugins:
  - search

  # - changelog
  # - search
  # - git-revision-date-localized:
  #     type: datetime
  #     timezone: Asia/Shanghai
  #     locale: zh
  #     enable_creation_date: true

nav:
  - Home: index.md
  - Computer Science: 
    - Computer Science/index.md
    - Programing Basis: 
      - Computer Science/Programming Basis/index.md
      - Shell: Computer Science/Programming Basis/Shell.md
      - Git: Computer Science/Programming Basis/Git.md
      - GNU Make: Computer Science/Programming Basis/GNU Make.md
      - Linux: Computer Science/Programming Basis/Linux.md
      - Regular Expression: Computer Science/Programming Basis/Regular Expression.md
      - MIT Missing Semester: Computer Science/Programming Basis/MIT Missing Semester.md
    - Programing language:
      - Computer Science/Programming Language/index.md
      - C: Computer Science/Programming Language/C.md
      - C++: Computer Science/Programming Language/C++.md
      - Python: Computer Science/Programming Language/Python.md
      - Java: Computer Science/Programming Language/Java.md
    - Algorithm: 
      - Computer Science/Algorithm/Algorithms and Data Structure.md
      - Algorithm Analysis: Computer Science/Algorithm/01 Algorithm Analysis.md
      - Linear List: Computer Science/Algorithm/02 Linear List.md
      - Trees: Computer Science/Algorithm/03 Trees.md
      - Hash: Computer Science/Algorithm/05 Hash.md
    - System:
      - Computer Science/System/index.md
      - CSAPP: 
        - Computer Science/System/CSAPP/CSAPP.md
        - A Tour of Computer Systems: Computer Science/System/CSAPP/Chapter1.md
        - Presenting and Manipulating Information: Computer Science/System/CSAPP/Chapter2.md
        - Machine-Level Representation of Programs: Computer Science/System/CSAPP/Chapter3.md
        - Processor Architecture: Computer Science/System/CSAPP/Chapter4.md
        - Optimizing Program Performance: Computer Science/System/CSAPP/Chapter5.md
        - The Memory Hierarchy: Computer Science/System/CSAPP/Chapter6.md
        - Linking: Computer Science/System/CSAPP/Chapter7.md
        - Exceptional Control Flow: Computer Science/System/CSAPP/Chapter8.md
        - Virtual Memory: Computer Science/System/CSAPP/Chapter9.md
        - System-Level I/O: Computer Science/System/CSAPP/Chapter10.md
        - Network Programming: Computer Science/System/CSAPP/Chapter11.md
        - Concurrent Programming: Computer Science/System/CSAPP/Chapter12.md
        - Supplement: ./Computer Science/System/CSAPP/Supplement.md
      - Assembly: Computer Science/System/Assembly.md
      - Verilog: Computer Science/System/Verilog.md
        
      # - 计算机系统 I: Computer Science/System/System1.md
    - Web:
      - Computer Science/Web/index.md
      - CSS: Computer Science/Web/CSS.md
      - HTML: Computer Science/Web/HTML.md
      - JavaScript: Computer Science/Web/Javascript.md
      - YAML: Computer Science/Web/YAML.md
  - Math:
    - Basic Courses: Math/index.md
    - Discrete Mathematics: 
      - Math/Discrete Mathematics/Discrete Mathematics.md
      - Propositional Logic: Math/Discrete Mathematics/01 Propositional Logic.md
      - Basic Structures: Math/Discrete Mathematics/02 Basic Structures.md
      - Graph Theory: Math/Discrete Mathematics/04 Graph Theory.md
    # - Algebra: Math/Algebra.md
    # - Analysis: Math/Analysis.md
    # - Topology: Math/General Topology.md
  - Reading: 
    - Reading/index.md
    - History: 
      - Reading/The Western Heritage.md
    - Taking Sides:
      - Reading/Taking Sides/index.md
      - Sustainability: Reading/Taking Sides/Sustainability.md
  - Varia: 
    - Learning Plan: Varia/Learning Plan.md
    - Booklist: Varia/Booklist.md
    - Typst Learning Report: Varia/Typst.md
    - Environment Configuration: Varia/Envs.md